version: "3.2"
services:
#  nginx:
#    build:
#      context: .
#    ports:
#      - 8080:80
#    networks:
#      - common_network
  frontend:
    build: .
    ports:
      - 9999:80
    stdin_open: true
    networks:
      - common_network
networks:
  common_network:
    external: true